# Generated by Django 5.0.1 on 2024-01-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=200)),
                ('emp_address', models.CharField(max_length=200)),
                ('hiring_date', models.DateField()),
                ('salary', models.FloatField()),
                ('designation', models.CharField(choices=[('TL', 'Team Lead'), ('Associate', 'Associate'), ('Manager', 'Manager')], max_length=100)),
                ('reporting_manager', models.CharField(choices=[('TL', 'Team Lead'), ('Manager', 'Manager'), ('Owner', 'Owner')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=250)),
                ('dept_floor', models.CharField(max_length=50)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSapp.employeemanagement')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateField()),
                ('salary_amt', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSapp.departmentmanagement')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSapp.employeemanagement')),
            ],
        ),
    ]
